package dpfm_api_input_reader

import (
	"data-platform-api-delivery-document-creates-rmq-kube/DPFM_API_Caller/requests"
)

func (sdc *SDC) ConvertToHeader() *requests.Header {
	data := sdc.Header
	return &requests.Header{
		DeliveryDocument:                data.DeliveryDocument,
		Buyer:                           data.Buyer,
		Seller:                          data.Seller,
		ReferenceDocument:               data.ReferenceDocument,
		ReferenceDocumentItem:           data.ReferenceDocumentItem,
		OrderID:                         data.OrderID,
		OrderItem:                       data.OrderItem,
		ContractType:                    data.ContractType,
		OrderValidityStartDate:          data.OrderValidityStartDate,
		OrderValidityEndDate:            data.OrderValidityEndDate,
		IssuingPlantTimeZone:            data.IssuingPlantTimeZone,
		ReceivingPlantTimeZone:          data.ReceivingPlantTimeZone,
		DocumentDate:                    data.DocumentDate,
		PlannedGoodsIssueDate:           data.PlannedGoodsIssueDate,
		PlannedGoodsIssueTime:           data.PlannedGoodsIssueTime,
		PlannedGoodsReceiptDate:         data.PlannedGoodsReceiptDate,
		PlannedGoodsReceiptTime:         data.PlannedGoodsReceiptTime,
		InvoiceDocumentDate:             data.InvoiceDocumentDate,
		HeaderCompleteDeliveryIsDefined: data.HeaderCompleteDeliveryIsDefined,
		HeaderDeliveryStatus:            data.HeaderDeliveryStatus,
		CreationDate:                    data.CreationDate,
		CreationTime:                    data.CreationTime,
		HeaderDeliveryBlockStatus:       data.HeaderDeliveryBlockStatus,
		HeaderIssuingBlockStatus:        data.HeaderIssuingBlockStatus,
		HeaderReceivingBlockStatus:      data.HeaderReceivingBlockStatus,
		GoodsIssueOrReceiptSlipNumber:   data.GoodsIssueOrReceiptSlipNumber,
		HeaderBillingStatus:             data.HeaderBillingStatus,
		HeaderBillingConfStatus:         data.HeaderBillingConfStatus,
		HeaderBillingBlockStatus:        data.HeaderBillingBlockStatus,
		HeaderGrossWeight:               data.HeaderGrossWeight,
		HeaderNetWeight:                 data.HeaderNetWeight,
		HeaderWeightUnit:                data.HeaderWeightUnit,
		Incoterms:                       data.Incoterms,
		BillFromParty:                   data.BillFromParty,
		BillToParty:                     data.BillToParty,
		BillFromCountry:                 data.BillFromCountry,
		BillToCountry:                   data.BillToCountry,
		Payer:                           data.Payer,
		Payee:                           data.Payee,
		IsExportImportDelivery:          data.IsExportImportDelivery,
		LastChangeDate:                  data.LastChangeDate,
		IssuingPlantBusinessPartner:     data.IssuingPlantBusinessPartner,
		IssuingPlant:                    data.IssuingPlant,
		ReceivingPlantBusinessPartner:   data.ReceivingPlantBusinessPartner,
		ReceivingPlant:                  data.ReceivingPlant,
		DeliverToParty:                  data.DeliverToParty,
		DeliverFromParty:                data.DeliverFromParty,
		TransactionCurrency:             data.TransactionCurrency,
		StockIsFullyConfirmed:           data.StockIsFullyConfirmed,
	}
}
